export const CREATE_PERMISSION = "CREATE";
export const DELETE_PERMISSION = "DELETE";
export const UPDATE_PERMISSION = "UPDATE";

export const RBAC_RESOURCE = "RBAC_RESOURCE";
export const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";
export const KYC_REQUESTS_RESOURCE = "KYC_REQUESTS_RESOURCE";

export const KYC_REQUESTS_DEP = "KYC_REQUESTS";

export const RequestStatus = {
  NONE: 0,
  PENDING: 1,
  ACCEPTED: 2,
  REJECTED: 3,
  DROPPED: 4,
};
